#############
GET http://localhost:8080/v1/user/2
Accept: application/json

#############
POST http://localhost:8080/v1/user
Accept: application/json
Content-Type: application/json

{
  "cityId": "4",
  "companyId": "2",
  "name": "Juan",
  "lastname": "juancito",
  "phone": "77747774",
  "birthday": "2001-08-15",
  "email": "jprueba52@gmail.com",
  "username": "juanprueba",
  "password": "ieje"
}

###
